# Generated by Django 3.2.4 on 2021-06-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name_eng',
            new_name='english_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name_kor',
            new_name='korean_name',
        ),
        migrations.AddField(
            model_name='user',
            name='kakao_identity',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
