# Generated by Django 3.2.4 on 2021-06-28 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20210623_0333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='passport_number',
            new_name='passport',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='flight_id',
            new_name='flight',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='passenger_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='passenger',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='air_ticket', to='tickets.passenger'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='pdf_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.IntegerField(unique=True),
        ),
    ]
