# Generated by Django 3.2.4 on 2021-06-30 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20210628_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='ticket',
        ),
        migrations.AddField(
            model_name='passenger',
            name='ticket',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pdf_url',
            field=models.URLField(null=True),
        ),
    ]
