# Generated by Django 3.2.4 on 2021-06-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20210623_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='flight_id',
            new_name='flight',
        ),
        migrations.AddField(
            model_name='ticket',
            name='pdf_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.IntegerField(unique=True),
        ),
    ]
