# Generated by Django 3.2.4 on 2021-06-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20210630_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='passenger',
            name='pdf_url',
            field=models.URLField(null=True),
        ),
    ]
