# Generated by Django 3.2.4 on 2021-06-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20210630_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(max_length=50),
        ),
    ]
